quarkus:
  http:
    port: 8086

mp:
  messaging:
    incoming:
      "login-events-in":
        connector: smallrye-kafka
        topic: player-login-events
        commit-strategy: throttled
    outgoing:
      "bonus-events-out":
        connector: smallrye-kafka
        topic: player-bonus-updates
        enable.idempotence: true
        acks: all
        retries: 5
        max.in.flight.requests.per.connection: 5
        key:
          serializer: org.apache.kafka.common.serialization.UUIDSerializer
